@startuml
'https://plantuml.com/class-diagram

class TodoManager {
    main()
    start()
}

class TodoController{
    model: TodoListModel
    'javafx event handlers
    initialize()
    saveListItems()
    loadListItems()
    clearItem()
    displayAll()
    displayCompleted()
    displayUncompleted()
    addItem()
    removeItem()
    editDescription()
    editDueDate()
    helpButton()
}

class FileManager {
    fileChooser()
    openFileLoadData()
    getDataFromFile()
    openFileSaveData()
    readFile()
    getDataFromTableView()
}

class TableManager{
    isClear()
}

class Item {
    -completed
    -description
    -dueDate
}

org.javafx.Application <|- TodoManager
TodoManager o--> TodoController
TodoController <--o Item
TodoController <--> FileManager
TodoController <- TableManager
Item o-> FileManager


@enduml